apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name  }}-configmap
data:
  myvalue: {{ .Values.favoriteDrink }}
  # 用 required 渲染, 后面的 "" 里面是错误信息, 后面跟着的是需要检查的值
  # 如果需要检查的值没有被设置, 那么执行 helm install 会报错并输出
  # "" 里面定义的错误信息
  value: {{ required "not set value: [.Values.who]" .Values.who }}
  #value: {{ required "A valid .Values.who entry required!" .Values.who }}
  #mykey: {{ .Custom.value }} 
