// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package gener

import (
	"wire/foobarbaz"
)

// Injectors from wire.go:

// Build() 创建一个 Baz 对象，其参数是 Baz 依赖的所有提供者
func InitializeBaz(x int) (*foobarbaz.Baz, error) {
	foo := foobarbaz.ProvideFoo(x)
	bar := foobarbaz.ProvideBar(foo)
	baz, err := foobarbaz.ProvideBaz(bar)
	if err != nil {
		return nil, err
	}
	return baz, nil
}

func InitializeBazz(x int) (*foobarbaz.Bazz, error) {
	foo := foobarbaz.ProvideFoo(x)
	bar := foobarbaz.ProvideBar(foo)
	baz, err := foobarbaz.ProvideBaz(bar)
	if err != nil {
		return nil, err
	}
	bazz := &foobarbaz.Bazz{
		Baz_: baz,
		Bar_: bar,
		Foo_: foo,
	}
	return bazz, nil
}
